# Generated by Django 4.1.5 on 2023-03-04 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта', max_length=120, verbose_name='Название')),
                ('desc', models.TextField(help_text='Описание проекта', verbose_name='Описание')),
                ('date_beg', models.DateField(default=datetime.date.today, help_text='Дата создания проекта', verbose_name='Создано')),
                ('date_end', models.DateField(blank=True, help_text='Дата завершения проекта', null=True, verbose_name='Завершено')),
                ('date_max', models.DateField(blank=True, help_text='Планируемая дата завершения проекта', null=True, verbose_name='План')),
                ('author', models.ForeignKey(blank=True, help_text='Автор проекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_projs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('uweb', models.ForeignKey(blank=True, help_text='Последний прользователь редактировавший проект', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название спринта', max_length=120, verbose_name='Название')),
                ('desc', models.TextField(help_text='Описание спринта', verbose_name='Описание')),
                ('date_beg', models.DateField(default=datetime.date.today, help_text='Дата создания спринта', verbose_name='Создано')),
                ('date_end', models.DateField(blank=True, help_text='Дата завершения спринта', null=True, verbose_name='Завершено')),
                ('date_max', models.DateField(blank=True, help_text='Планируемая дата завершения спринта', null=True, verbose_name='План')),
                ('author', models.ForeignKey(blank=True, help_text='Автор спринта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_sprints', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('proj', models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, related_name='proj_sprints', to='app_task.proj', verbose_name='Проект')),
                ('uweb', models.ForeignKey(blank=True, help_text='Последний прользователь редактировавший спринт', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название задачи', max_length=120, verbose_name='Название')),
                ('desc', models.TextField(help_text='Описание задачи', verbose_name='Описание')),
                ('date_beg', models.DateField(default=datetime.date.today, help_text='Дата создания задачи', verbose_name='Создано')),
                ('date_end', models.DateField(blank=True, help_text='Дата завершения задачи', null=True, verbose_name='Завершено')),
                ('date_max', models.DateField(blank=True, help_text='Планируемая дата завершения задачи', null=True, verbose_name='План')),
                ('author', models.ForeignKey(blank=True, help_text='Автор задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, help_text='Предыдущая задача', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_nexts', to='app_task.task', verbose_name='Зависит от')),
                ('proj', models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, related_name='proj_tasks', to='app_task.proj', verbose_name='Проект')),
                ('sprint', models.ForeignKey(blank=True, help_text='Спринт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='app_task.sprint', verbose_name='Спринт')),
                ('user', models.ForeignKey(blank=True, help_text='Исполнитель задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('uweb', models.ForeignKey(blank=True, help_text='Последний прользователь редактировавший задачу', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(help_text='Выполненная работа по задаче', verbose_name='Что сделано')),
                ('date_end', models.DateTimeField(default=datetime.datetime.now, help_text='Дата завершения шага', verbose_name='Завершён')),
                ('author', models.ForeignKey(blank=True, help_text='Исполнитель шага', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_steps', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('task', models.ForeignKey(help_text='Задача', on_delete=django.db.models.deletion.CASCADE, related_name='task_steps', to='app_task.task', verbose_name='Задача')),
            ],
        ),
    ]
