# Generated by Django 4.1.5 on 2023-02-06 02:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название проекта",
                        max_length=120,
                        verbose_name="Название",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        help_text="Описание проекта",
                        max_length=250,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "date_beg",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text="Дата создания проекта",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата завершения проекта",
                        null=True,
                        verbose_name="Завершено",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автор проекта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_proj",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sprints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название спринта",
                        max_length=120,
                        verbose_name="Название",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        help_text="Описание спринта",
                        max_length=250,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "date_beg",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text="Дата создания спринта",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата завершения спринта",
                        null=True,
                        verbose_name="Завершено",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автор спринта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_sprint",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название задачи",
                        max_length=120,
                        verbose_name="Название",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        help_text="Описание задачи",
                        max_length=250,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "date_beg",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text="Дата создания задачи",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата завершения задачи",
                        null=True,
                        verbose_name="Завершено",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автор задачи",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "proj",
                    models.ForeignKey(
                        blank=True,
                        help_text="Проект",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proj_tasks",
                        to="app_task.projs",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Спринт",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint_tasks",
                        to="app_task.sprints",
                        verbose_name="Спринт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_beg",
                    models.TextField(
                        help_text="Необходимая работа по шагу",
                        max_length=250,
                        verbose_name="Что сделать",
                    ),
                ),
                (
                    "work_end",
                    models.TextField(
                        blank=True,
                        help_text="Выполненая работа по шагу",
                        max_length=250,
                        null=True,
                        verbose_name="Что сделано",
                    ),
                ),
                (
                    "date_beg",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text="Дата создания шага",
                        verbose_name="Создан",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата завершения шага",
                        null=True,
                        verbose_name="Завершён",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автор шага",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Задача",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_steps",
                        to="app_task.tasks",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Исполнитель шага",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steps_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
        ),
    ]
