# Generated by Django 4.1.5 on 2023-02-06 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_task", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projs",
            new_name="Proj",
        ),
        migrations.RenameModel(
            old_name="Sprints",
            new_name="Sprint",
        ),
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
        migrations.RenameModel(
            old_name="TaskSteps",
            new_name="TaskStep",
        ),
    ]
