# Generated by Django 4.1.5 on 2023-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstep",
            name="auto_create",
            field=models.BooleanField(
                default=True,
                help_text="Запись создана автоматически",
                verbose_name="Автосоздано",
            ),
        ),
    ]
