# Generated by Django 4.1.5 on 2023-02-08 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_task", "0002_rename_projs_proj_rename_sprints_sprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="proj",
            field=models.ForeignKey(
                default=1,
                help_text="Проект",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proj_sprints",
                to="app_task.proj",
                verbose_name="Проект",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proj",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Автор проекта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_projs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Автор спринта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_sprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="proj",
            field=models.ForeignKey(
                default=1,
                help_text="Проект",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proj_tasks",
                to="app_task.proj",
                verbose_name="Проект",
            ),
            preserve_default=False,
        ),
    ]
