# Generated by Django 4.1.5 on 2023-03-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_proj_name_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='name_upper',
            field=models.CharField(blank=True, help_text='Название проекта в верхнем регистре', max_length=120, null=True, verbose_name='НАЗВАНИЕ'),
        ),
    ]
