# Generated by Django 4.1.5 on 2023-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0004_alter_proj_name_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='name_upper',
            field=models.CharField(blank=True, default='', help_text='Название проекта в ВЕРХНЕМ регистре', max_length=120, verbose_name='НАЗВАНИЕ'),
            preserve_default=False,
        ),
    ]
