# Generated by Django 4.1.5 on 2023-02-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_task", "0004_alter_task_proj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskstep",
            name="author",
        ),
        migrations.RemoveField(
            model_name="taskstep",
            name="date_beg",
        ),
        migrations.RemoveField(
            model_name="taskstep",
            name="work_beg",
        ),
        migrations.RemoveField(
            model_name="taskstep",
            name="work_end",
        ),
        migrations.AddField(
            model_name="proj",
            name="date_max",
            field=models.DateTimeField(
                blank=True,
                help_text="Планируемая дата завершения проекта",
                null=True,
                verbose_name="План",
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="date_max",
            field=models.DateTimeField(
                blank=True,
                help_text="Планируемая дата завершения спринта",
                null=True,
                verbose_name="План",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="date_max",
            field=models.DateTimeField(
                blank=True,
                help_text="Планируемая дата завершения задачи",
                null=True,
                verbose_name="План",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Исполнитель задачи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="taskstep",
            name="desс",
            field=models.TextField(
                blank=True,
                help_text="Выполненая работа по задаче",
                max_length=250,
                null=True,
                verbose_name="Что сделано",
            ),
        ),
        migrations.AlterField(
            model_name="taskstep",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Исполнитель шага",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_steps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
    ]
