# Generated by Django 4.1.5 on 2023-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_remove_taskstep_author_remove_taskstep_date_beg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='desc',
            field=models.TextField(help_text='Описание проекта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='desc',
            field=models.TextField(help_text='Описание спринта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(help_text='Описание задачи', verbose_name='Описание'),
        ),
    ]
