# Generated by Django 4.1.5 on 2023-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0006_alter_proj_desc_alter_sprint_desc_alter_task_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='desс',
            field=models.TextField(blank=True, help_text='Выполненая работа по задаче', null=True, verbose_name='Что сделано'),
        ),
    ]
