# Generated by Django 4.1.5 on 2023-02-09 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0007_alter_taskstep_desс'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата завершения шага', verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='desс',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', help_text='Выполненая работа по задаче', verbose_name='Что сделано'),
            preserve_default=False,
        ),
    ]
