# Generated by Django 4.1.5 on 2023-02-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0008_alter_taskstep_date_end_alter_taskstep_desс'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj',
            old_name='desc',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='desc',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='text',
        ),
    ]
