# Generated by Django 4.1.5 on 2023-02-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0009_rename_desc_proj_text_rename_desc_sprint_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj',
            old_name='text',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='text',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='taskstep',
            old_name='desс',
            new_name='desc',
        ),
    ]
