# Generated by Django 4.1.5 on 2023-02-14 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_task", "0010_rename_text_proj_desc_rename_text_sprint_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proj",
            name="date_beg",
            field=models.DateField(
                default=datetime.datetime.now,
                help_text="Дата создания проекта",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="proj",
            name="date_end",
            field=models.DateField(
                blank=True,
                help_text="Дата завершения проекта",
                null=True,
                verbose_name="Завершено",
            ),
        ),
        migrations.AlterField(
            model_name="proj",
            name="date_max",
            field=models.DateField(
                blank=True,
                help_text="Планируемая дата завершения проекта",
                null=True,
                verbose_name="План",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="date_beg",
            field=models.DateField(
                default=datetime.datetime.now,
                help_text="Дата создания спринта",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="date_end",
            field=models.DateField(
                blank=True,
                help_text="Дата завершения спринта",
                null=True,
                verbose_name="Завершено",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="date_max",
            field=models.DateField(
                blank=True,
                help_text="Планируемая дата завершения спринта",
                null=True,
                verbose_name="План",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_beg",
            field=models.DateField(
                default=datetime.datetime.now,
                help_text="Дата создания задачи",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_end",
            field=models.DateField(
                blank=True,
                help_text="Дата завершения задачи",
                null=True,
                verbose_name="Завершено",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_max",
            field=models.DateField(
                blank=True,
                help_text="Планируемая дата завершения задачи",
                null=True,
                verbose_name="План",
            ),
        ),
        migrations.AlterField(
            model_name="taskstep",
            name="date_end",
            field=models.DateField(
                default=datetime.datetime.now,
                help_text="Дата завершения шага",
                verbose_name="Завершён",
            ),
        ),
    ]
