# Generated by Django 4.1.5 on 2023-02-16 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_task", "0011_alter_proj_date_beg_alter_proj_date_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proj",
            name="date_beg",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Дата создания проекта",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="date_beg",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Дата создания спринта",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_beg",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Дата создания задачи",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="taskstep",
            name="date_end",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Дата завершения шага",
                verbose_name="Завершён",
            ),
        ),
    ]
