# Generated by Django 4.1.5 on 2023-02-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0012_alter_proj_date_beg_alter_sprint_date_beg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Предыдущиая задача', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_nexts', to='app_task.task', verbose_name='Зависит от'),
        ),
    ]
