# Generated by Django 4.1.5 on 2023-02-25 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_task', '0014_alter_task_proj_alter_task_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstep',
            name='user',
        ),
        migrations.AddField(
            model_name='taskstep',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Исполнитель шага', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_steps', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
