# Generated by Django 4.1.5 on 2023-02-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_task', '0015_remove_taskstep_user_taskstep_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uweb',
            field=models.ForeignKey(blank=True, help_text='Последний прользовател редактировавший задачу', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
    ]
