# Generated by Django 4.1.5 on 2023-02-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0017_proj_uweb_sprint_uweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата завершения шага', verbose_name='Завершён'),
        ),
    ]
